### ISSUE TITLE
pdf version?

### ISSUE THREAD

**Issue by laoshaw** [gibbok/typescript-book#107]
can we have a pdf version? Thanks!

**Comment by gibbok** [comment]
Sounds as a good idea! I write a note in my todo list... Thanks for sharing!

**Comment by gspgsp** [comment]
hope to have a pdf version too.

**Comment by gibbok** [comment]
@gspgsp 
Hi, I was able to generate PDFs in both EN and CN in this PR:
https://github.com/gibbok/typescript-book/issues/107

You can find the PDF files here:
https://github.com/gibbok/typescript-book/tree/main/downloads

Hope this helps! Please let me know if you find any issues.
Thanks for your interest in the book!

**Comment by gibbok** [comment]
Thanks for your feedback! I will add this feature to my backlog, but unfortunately, I don't have time to work on it right now. Temporarily, I think you can solve this issue by using some tools like:
https://handyoutlinerfo.sourceforge.net/
Or if you like to contribute any PR is welcome 😄 . Thanks again!

**Comment by gibbok** [comment]
@laoshaw

Hi, I was able to add the TOC(table of content) to the PDFs, also I improved a bit the layout

PR:
https://github.com/gibbok/typescript-book/pull/114

Books for download:
https://github.com/gibbok/typescript-book/tree/main/downloads

Thanks for your initial ticket and happy reading!
