### ISSUE TITLE
Do you accept a PR with Spanish translation?

### ISSUE THREAD

**Issue by Bryan-Herrera-DEV** [gibbok/typescript-book#19]
I think it is a very good contribution and I would like to contribute with the Spanish translation, so we all could enjoy this content.
I look forward to hearing from you.
Best regards.

**Comment by echeverriadev** [comment]
I would like to help with the translation as well

**Comment by gibbok** [comment]
Hi thanks you both for your comments and interest.
Yes off course I would love to see a Spanish translation. Feel free to make a PR any time.
Thanks again for your help and support.

**Comment by gibbok** [comment]
@Bryan-Herrera-DEV @echeverriadev  
Hi there!  ust a heads-up, I'll be closing this ticket. Whenever you're ready, feel free to submit a pull request. If you need help or have questions, feel free to ask. Thanks for your contribution and support!
