### ISSUE TITLE
Persian Translation?

### ISSUE THREAD

**Issue by mkazemiraz** [gibbok/typescript-book#31]
Hello,

I hope you're doing well. I recently came across your repository. I noticed that your repository doesn't have a Persian translation, and I'm interested in contributing by adding a Persian translation if you're open to it.

As a Persian-speaking user, I believe adding a Persian translation to your repository can help the Persian-speaking developer community benefit from your project to the fullest extent.

Are you interested in the idea of adding a Persian translation to your repository? If you're open to it, I would be delighted to collaborate and provide smooth and accurate translations for you.

I'm looking forward to hearing from you. If you have any questions or requests, please let me know.

**Comment by gibbok** [comment]
Thanks for your message and interest.
Yes I believe a Persian translation would be a great addition. I would be delighted to have your contribution.
Thanks again.

**Comment by gibbok** [comment]
@mkazemiraz Hi there! I wanted to let you know that I'll be closing this ticket. Feel free to take your time and submit a pull request whenever you're ready. If you need any assistance or have questions, don't hesitate to reach out. Thanks so much for your involvement – it's greatly appreciated!
