### ISSUE TITLE
 Fix typo, "preserver" to "preserve" in Chinese version

### ISSUE THREAD

**Issue by gibbok** [gibbok/typescript-book#34]
Fix typo, "preserver" to "preserve". Visible in line 564 of the Chinese translation.

**Comment by kuriacka** [comment]
Already merged - https://github.com/gibbok/typescript-book/pull/33

**Comment by gibbok** [comment]
I think this issue is still relevant in the Chinese version.

**Comment by gibbok** [comment]
Fixed here thanks for reporting
https://github.com/gibbok/typescript-book/pull/38
