### ISSUE TITLE
 some advice⚗

### ISSUE THREAD

**Issue by webvs2** [gibbok/typescript-book#55]
As your audience grows, consider adding some online experiences to help your readers. Here are my suggestions：
1. Add an online playground, you can practice while learning, practice can better deepen understanding and memory
2. Add the right navigation bar for quick location
3. Adding a bookmark feature, I want to store some difficult points in a place that can be quickly returned for easy reading back

**Comment by gibbok** [comment]
Hi there! Thank you so much for your advice and suggestions. I really appreciate it!

Currently, the book is only available in markdown and epub formats, and we don't have a website version yet. But we'll definitely consider creating one in the future!

Regarding your suggestions, here's some friendly feedback:

1. For practicing and testing your TypeScript code, I highly recommend trying out [TypeScript Playground](https://www.typescriptlang.org/play). It's a fantastic tool!

2. Unfortunately, we can't implement the specific feature you mentioned in the Markdown doc at the moment. But don't worry, there might be other ways we can improve the user experience when we create the website version!

3. Good news! You can bookmark each section of the book. Simply move your cursor over any subtitle, and in your browser, you can bookmark the URL. For example, you can bookmark this link: [Book Subsection Bookmark](https://github.com/gibbok/typescript-book#modern-javascript-now-downleveling).

If you have any questions, more ideas or need further assistance, please don't hesitate to reach out. Thanks again for your valuable input. 😊

**Comment by webvs2** [comment]
Wow, thanks for the responses to my suggestions, these solutions can implement my ideas. So far, this TS manual is really good, I like it, it helps me learn ts, and I hope I can contribute to building better websites in the future.😊😁

**Comment by gibbok** [comment]
I'm delighted to hear that you find the book useful! 🌟 I'll go ahead and close this ticket for now. But remember, you're always welcome to open a pull request whenever you like! Your contributions are truly appreciated. Thanks again for being a part of our community! 😊
