### ISSUE TITLE
Possible Update on Revered Mapping of Enums?

### ISSUE THREAD

**Issue by jerrylususu** [gibbok/typescript-book#60]
I have been using TypeScript for a while but haven't checked out any materials that systematically explain its inner workings. I found this book to be truly helpful. Thank you for your wonderful work!

In the section about [reversed mapping of enums](https://github.com/gibbok/typescript-book#reverse-mapping), there is a code example showcasing a `Language` enum with 2 string enum members. However, there are a few minor issues with that example. Firstly, it does not demonstrate how the reverse mapping maps the value back to its key. Secondly, according to [the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings), string enum members do not automatically generate a reverse mapping.

Perhaps the following example would be better? I can create a pull request if you find it acceptable.
```typescript
enum Grade {
  A = 90,
  B = 80,
  C = 70
}

// reverse mapping maps an enum value back to its corresponding key
const myGrade = Grade.A;
console.log(Grade[myGrade]) // => "A"
console.log(Grade[90]) // => "A"
```

**Comment by jerrylususu** [comment]
Added a string enum member to the example for better clarity. Also fixed zh-cn translate of this section.

**Comment by gibbok** [comment]
@jerrylususu Thanks for catching that mistake and your PR with an improved version!
