### ISSUE TITLE
Titles capitalization

### ISSUE THREAD

**Issue by gibbok** [gibbok/typescript-book#81]
Improve titles capitalization in the English version.

**Comment by Arsaluddin** [comment]
Hey! can you please assign me this issue i will do it ☺

**Comment by gibbok** [comment]
Sure, thanks for your help on this!

**Comment by Arsaluddin** [comment]
> Sure, thanks for your help on this!

I will try to do it ASAP ☺

**Comment by Arsaluddin** [comment]
Can you please give me one example , that help me to figure out what exactly I have to do.

**Comment by gibbok** [comment]
Hi, you would need to look at Capitalization Rules in English (USA) and update the content when necessary. Thanks for your help on this!

**Comment by gibbok** [comment]
Hi, any updates on this?

**Comment by A-4-Atom** [comment]
Can you elaborate a little, like what's wrong. Give me some code or screenshot. I'll try to fix it. :)
